### ISSUE TITLE
/Users/adb/workspace/merge-yml/bin does not exist

### ISSUE THREAD

**Issue by balthorium** [cobbzilla/merge-yml#3]
Hey Jonathan - first, thank you for sharing this.  I'm hoping it will help me out of a jam.

Second, I'm finding that the build fails due to a missing bin directory at the root level.  Is it possible that you have code that didn't get added to the repo?

**Comment by cobbzilla** [comment]
It should be there. I'll re-add it since it seems to have gotten "lost".
